### ISSUE TITLE
Error when running a job

### ISSUE THREAD

**Issue by Reinmar** [benderjs/benderjs#253]
I regularly get this:

```
Unsupported node type:Super
error: [middleware-jobs]  TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.Expression.Property (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2139:22)
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at /www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2220:38
    at withIndent (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:582:9)
    at CodeGenerator.Expression.ObjectPattern (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2216:13)
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.generateAssignment (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:1005:22)
    at CodeGenerator.generateFunctionParams (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:914:38)
    at CodeGenerator.generateFunctionBody (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:940:23)
{ range: [ 1329, 1334 ],
  loc:
   SourceLocation {
     start: Position { line: 45, column: 3 },
     end: { line: 45, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 6182, 6187 ],
  loc:
   SourceLocation {
     start: Position { line: 223, column: 14 },
     end: { line: 223, column: 19 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 714, 719 ],
  loc:
   SourceLocation {
     start: Position { line: 29, column: 3 },
     end: { line: 29, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2131, 2136 ],
  loc:
   SourceLocation {
     start: Position { line: 52, column: 3 },
     end: { line: 52, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1194, 1199 ],
  loc:
   SourceLocation {
     start: Position { line: 41, column: 3 },
     end: { line: 41, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2095, 2100 ],
  loc:
   SourceLocation {
     start: Position { line: 52, column: 3 },
     end: { line: 52, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1427, 1432 ],
  loc:
   SourceLocation {
     start: Position { line: 48, column: 3 },
     end: { line: 48, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1988, 1993 ],
  loc:
   SourceLocation {
     start: Position { line: 47, column: 3 },
     end: { line: 47, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1520, 1525 ],
  loc:
   SourceLocation {
     start: Position { line: 46, column: 3 },
     end: { line: 46, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1430, 1435 ],
  loc:
   SourceLocation {
     start: Position { line: 45, column: 3 },
     end: { line: 45, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1632, 1637 ],
  loc:
   SourceLocation {
     start: Position { line: 46, column: 3 },
     end: { line: 46, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2367, 2372 ],
  loc:
   SourceLocation {
     start: Position { line: 63, column: 3 },
     end: { line: 63, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
error: Test error: Uncaught Error: Deferment unlock timeout - "2" never unlocked
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/undo/undo - FAILED
error: /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/undo/undo FAILED
Script error

Uncaught Error: Deferment unlock timeout - "2" never unlocked
warn: [coverage] No coverage info was collected for /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/undo/undo
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/composer/deletecontents
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/composer/deletecontents - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/schema/schemaitem
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/schema/schemaitem - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/utils/comparearrays
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/utils/comparearrays - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/view/observer/observer
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/view/observer/observer - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/ckeditor5/load
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/ckeditor5/load - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/delta/renamedelta
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/engine/model/delta/renamedelta - PASSED
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 runs test /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/ui/editableui/editableui
{ range: [ 928, 933 ],
  loc:
   SourceLocation {
     start: Position { line: 36, column: 3 },
     end: { line: 36, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 847, 852 ],
  loc:
   SourceLocation {
     start: Position { line: 30, column: 6 },
     end: { line: 30, column: 11 } },
  type: 'Super' }
Unsupported node type:Super
info: Client dadcffe9-5332-42bf-86c0-2a8940e67e27 completed /jobs/Yoxe9SvbVC0PujTY/tests/build/amd/tests/ui/editableui/editableui - PASSED
```

This pauses a job for around half a minute which is extremely irritating. I've started having this when I upgraded Node to 6.x, but it's also possible that this is caused by some new code in CKEditor 5 project.

Unfortunately together with recent issues with benderjs-coverage, every time I run a job I have to spend additional minute waiting for it to finish.

**Comment by Reinmar** [comment]
The error has changed a bit recently :D.

```
error: [middleware-jobs]  TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.Expression.Property (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2139:22)
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at /www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2220:38
    at withIndent (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:582:9)
    at CodeGenerator.Expression.ObjectPattern (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2216:13)
    at CodeGenerator.generateExpression (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.generateAssignment (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:1005:22)
    at CodeGenerator.generateFunctionParams (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:914:38)
    at CodeGenerator.generateFunctionBody (/www/ckeditor5/ckeditor5/node_modules/escodegen/escodegen.js:940:23)
error: Test error: Uncaught RangeError: Maximum call stack size exceeded
```

**Comment by Reinmar** [comment]
I checked on Node 5 (5.11.0 to be precise) and got this error again.

As you can see, it starts in `model-selection-to-view-converters` what made me think that it may be a test issue... but the test seem to pass just fine when run either from a dashboard or directly.

```info: Client e5fc7386-b338-48fc-befc-d92977321359 runs test /jobs/iGUPM6zd7XgZ9fs7/tests/build/amd/tests/engine/conversion/model-selection-to-view-converters
{ range: [ 1329, 1334 ],
  loc:
   SourceLocation {
     start: Position { line: 45, column: 3 },
     end: { line: 45, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 6182, 6187 ],
  loc:
   SourceLocation {
     start: Position { line: 223, column: 14 },
     end: { line: 223, column: 19 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2370, 2375 ],
  loc:
   SourceLocation {
     start: Position { line: 64, column: 6 },
     end: { line: 64, column: 11 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1366, 1371 ],
  loc:
   SourceLocation {
     start: Position { line: 45, column: 3 },
     end: { line: 45, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2107, 2112 ],
  loc:
   SourceLocation {
     start: Position { line: 65, column: 18 },
     end: { line: 65, column: 23 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2566, 2571 ],
  loc:
   SourceLocation {
     start: Position { line: 82, column: 10 },
     end: { line: 82, column: 15 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 993, 998 ],
  loc:
   SourceLocation {
     start: Position { line: 37, column: 3 },
     end: { line: 37, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1456, 1461 ],
  loc:
   SourceLocation {
     start: Position { line: 42, column: 3 },
     end: { line: 42, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1427, 1432 ],
  loc:
   SourceLocation {
     start: Position { line: 48, column: 3 },
     end: { line: 48, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
error: [middleware-jobs]  TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/www/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.Expression.Property (/www/ckeditor5/node_modules/escodegen/escodegen.js:2139:22)
    at CodeGenerator.generateExpression (/www/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at /www/ckeditor5/node_modules/escodegen/escodegen.js:2220:38
    at withIndent (/www/ckeditor5/node_modules/escodegen/escodegen.js:582:9)
    at CodeGenerator.Expression.ObjectPattern (/www/ckeditor5/node_modules/escodegen/escodegen.js:2216:13)
    at CodeGenerator.generateExpression (/www/ckeditor5/node_modules/escodegen/escodegen.js:2427:28)
    at CodeGenerator.generateAssignment (/www/ckeditor5/node_modules/escodegen/escodegen.js:1005:22)
    at CodeGenerator.generateFunctionParams (/www/ckeditor5/node_modules/escodegen/escodegen.js:914:38)
    at CodeGenerator.generateFunctionBody (/www/ckeditor5/node_modules/escodegen/escodegen.js:940:23)
error: Test error: Uncaught RangeError: Maximum call stack size exceeded
{ range: [ 2118, 2123 ],
  loc:
   SourceLocation {
     start: Position { line: 57, column: 3 },
     end: { line: 57, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 718, 723 ],
  loc:
   SourceLocation {
     start: Position { line: 35, column: 3 },
     end: { line: 35, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2131, 2136 ],
  loc:
   SourceLocation {
     start: Position { line: 52, column: 3 },
     end: { line: 52, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1194, 1199 ],
  loc:
   SourceLocation {
     start: Position { line: 41, column: 3 },
     end: { line: 41, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2095, 2100 ],
  loc:
   SourceLocation {
     start: Position { line: 52, column: 3 },
     end: { line: 52, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1988, 1993 ],
  loc:
   SourceLocation {
     start: Position { line: 47, column: 3 },
     end: { line: 47, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1520, 1525 ],
  loc:
   SourceLocation {
     start: Position { line: 46, column: 3 },
     end: { line: 46, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1430, 1435 ],
  loc:
   SourceLocation {
     start: Position { line: 45, column: 3 },
     end: { line: 45, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 1632, 1637 ],
  loc:
   SourceLocation {
     start: Position { line: 46, column: 3 },
     end: { line: 46, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
{ range: [ 2367, 2372 ],
  loc:
   SourceLocation {
     start: Position { line: 63, column: 3 },
     end: { line: 63, column: 8 } },
  type: 'Super' }
Unsupported node type:Super
error: Test error: Uncaught RangeError: Maximum call stack size exceeded
```

**Comment by Reinmar** [comment]
Got the same issue in a different test now, so it's not a test problem.

**Comment by Reinmar** [comment]
I've done some more debugging and it seems that it's Istanbul's fault. I upgraded it to 0.4.x by forking benderjs-coverage and got different kind of errors. Actually - just one error and this time quite clearly in a very complex ES6 feature – default params with destructuring:

```js
	constructor(
		{
			boundaries = null,
			startPosition,
			direction = 'FORWARD',
			singleCharacters = false,
			shallow = false,
			ignoreElementEnd = false,
		} = {}
	)
```

So it looks bad. Even the latest Istanbul version doesn't handle this yet (if I'm right of course). But we'll need to check it.

**Comment by pjasiun** [comment]
Same issue here after updating Node from 4.4.4 to 5.9.1.
